# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_livro_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.CharField(max_length=1500),
        ),
    ]
