# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 15:01
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160725_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=stdimage.models.StdImageField(default=False, upload_to='capas'),
        ),
    ]
