# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160801_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='ano_nasc',
            new_name='anoNasc',
        ),
    ]
