# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160815_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
